(See Desc) Dex Update
new-meta-incorporated/pokemon-showdown pull request #41
Opened 2022-05-15 21:31 UTC by matteoruscitti

Adds:
- Roedrunna
- Maliceros
- Breechon, Nimbichon
- Leviorca
- Squimshi, Gummelid
- Alivolt
- Fintricity
- Terrator
- Gengar Alola
- Intricat
(The latter two can be found exactly where their prevos are. Intricat evolves from Delcatty. I need a review on Gengar-Alola. There are still Pokemon missing. Trapinch-Orre line is missing, as is Vikavolt-Unova line. _In order for this update to be marked done, we must also complete tiering data and learnsets._ **Do not push this change until this is completed.**

**DEADLINE IS MAY 25, 2022**

2022-05-15 23:58 UTC, GamR-the-Great requested changes

2022-05-15 23:58 UTC, GamR-the-Great commented on data/pokedex.ts
> +		abilities: {0: "Cloud Nine", 1: "Fur Coat", H: "Aerilate"},
Breechon and Nimbichon are part of the same line, but you missed the evo & prevo stuff completely here.

2022-05-15 23:58 UTC, GamR-the-Great commented on data/pokedex.ts
> +		num: 10098,
Same with Squimshi & Gummelid

2022-05-16 03:03 UTC, jmf61 commented
Added the tiering for Roedrunna through Terrator, still need tiering for Gengar-Alola and all mons listed below

2022-05-16 03:40 UTC, jmf61 commented
Added learnsets for Roedrunna through Terrator, still need learnsets for Gengar-Alola and all mons listed below

2022-05-16 20:41 UTC, matteoruscitti commented
fintricity has "hydropum" rather than hydropump. Did the tool generate the miss spell or were these typed manually?

2022-05-20 02:30 UTC, jmf61 commented
> fintricity has "hydropum" rather than hydropump. Did the tool generate the miss spell or were these typed manually?

the submission had it misspelled, so autoformatting meant the code had same misspell

2022-05-25 04:23 UTC, DomTom22 approved these changes

2022-05-25 04:25 UTC, merged